### ISSUE TITLE
Using vdiffr with DiagrammeR

### ISSUE THREAD

**Issue by Sumidu** [r-lib/vdiffr#102]
Hi,
I have been trying to get vdiffr to work with the DiagrammeR package. 
Sadly, the DiagrammerRsvg package used for exporting svg uses the rsvg under the hood which seems to behave non-deterministically in naming some entities. 
I have now written my own "writer" function, which basically uses the pre-raw SVG string and puts it into a file.
When calling `manage_cases` everything is fine. Every case is validated. However, when running R cmd test, all cases fail.
How could I fix this? Can I debut the test-cases somehow?

**Comment by lionel-** [comment]
See the `vdiffr.Rout.fail` log file. You will need to make sure the SVG generation does not depend on any system library because that will be a source of differences across platforms (e.g. in Github Actions or the computers of other contributors). This is why vdiffr embeds its own SVG engine.
