### ISSUE TITLE
expect_doppleganger throws warnings due to expect_snapshot_file deprecation of binary arg

### ISSUE THREAD

**Issue by arnaud-feldmann** [r-lib/vdiffr#110]
Hi @lionel- ,

Hope you're doing well,

As it is stated in my title, `expect_doppleganger` throws a warning because of the deprecation of **binary** arg of `testthat::expect_snapshot_file`.

As you've done both commits, it is likely that you're aware of the issue. Through, in your master branch of vdiffr, it seems like the **binary** arg of `testthat::expect_snapshot_file` is still called.

![image](https://user-images.githubusercontent.com/60670870/122389676-7704f600-cf71-11eb-8add-05a4fdac2ade.png)

Keep up the good work !

**Comment by lionel-** [comment]
I forgot about that and the warning didn't surface in vdiffr tests :(

Thanks!
