### ISSUE TITLE
Add libpng to `SystemRequirements`?

### ISSUE THREAD

**Issue by glin** [r-lib/vdiffr#111]
Hi, vdiffr appears to require libpng, but it isn't listed in the `SystemRequirements` field. Would you be open to adding libpng (and any other system requirements I may have missed) to `SystemRequirements`? This would help Linux users install and run the package, and also RSPM with building Linux binary packages for vdiffr.

For example, something like this would work:

```
SystemRequirements: C++11, libpng
```

**Comment by lionel-** [comment]
yup sounds good. Would you like to send a PR? cc @thomasp85
