### ISSUE TITLE
R-devel issues (R > 4.1)

### ISSUE THREAD

**Issue by pat-s** [r-lib/vdiffr#117]
We see [these issues](https://github.com/mlr-org/mlr3viz/runs/3803525719#step:16:169) on R-devel (R-release, 4.1.1 is fine).

Reading all the threads about R-devel related issues, I suspsect there might be new trouble eventually? In #86 the changes were announced for R 4.1 but now were on the way to 4.2, so the discussion in #86 might not apply anymore?

**Comment by lionel-** [comment]
Thanks for the heads up.

Hopefully we will be able to leverage the new "variant" snapshots of the recent testthat release: https://www.tidyverse.org/blog/2021/10/testthat-3-1/#snapshot-tests

**Comment by IndrajeetPatil** [comment]
Since `R 4.2` release is only a few days away now, I was wondering if there are any updates on this issue.

**Comment by maksymiuks** [comment]
Hi @lionel- 

Do you have any plans to reintroduce the testing mechanism? Currently, the testing suite is only run for R below 4.1.0

**Comment by lionel-** [comment]
I think it's only run for R equal or above 4.1.0.

**Comment by maksymiuks** [comment]
They are not, at least according to my experience. Looking at the testthat.R content they were turned off roughly 2 years ago:

https://github.com/r-lib/vdiffr/blob/main/tests/testthat.R#L2-L6

so for instance  `tools::testInstalledPackage` runs them only for R below 4.1.0. Tested it also locally on R 4.1.3 and 4.2.1

**Comment by maksymiuks** [comment]
Oh, pardon me @lionel- now I see I must have misinterpreted the matter of this issue. I apologize. Want me to migrate it to a new, appropriate one?

**Comment by lionel-** [comment]
It's alright we can keep track of this here, thanks!
