### ISSUE TITLE
Adding a `variant` support for snapshots?

### ISSUE THREAD

**Issue by danielinteractive** [r-lib/vdiffr#125]
Hello team,
first of all thanks for `vdiffr`- very important for the testing of plot functions.
One question - did you consider already adding `variant` support similar as `shinytest2` e.g. has?
That could come in handy to save snapshots from different `ggplot2` package versions e.g.

**Comment by lionel-** [comment]
yes in fact part of the motivation for adding a `variant` mechanism in testthat was to support multiple svg snapshots for different R versions..

**Comment by lionel-** [comment]
Now on CRAN!
