### ISSUE TITLE
Running snapshot_review() of a package checked with devtools::check() ?

### ISSUE THREAD

**Issue by Qile0317** [r-lib/vdiffr#133]
For the dev branch of [my package](https://github.com/Qile0317/APackOfTheClones/tree/dev), on my device locally, running `devtools::test()` works, but `devtools::check()` [fails for a very specific case](https://github.com/Qile0317/APackOfTheClones/actions/runs/4972878970/jobs/8898356778) to do with a plotting function tested by `vdiffr`.  I've read the [Usual Suspects for specific failure modes](https://github.com/hadley/r-pkgs/issues/483) issue and still don't know the problem, as another function which uses this tested function does pass the test, so its probably some hidden, obscure bug? 

Regardless, the output from `devtools::check` states to `Run testthat::snapshot_review('plot_API/')` to review changes` but I can't access the temporary environment. Is there a way to do so?

The most peculiar thing is that if I run `devtools::build()`, and then run `rcmdcheck::rcmdcheck()` on the built tarball, the check passes.

**Comment by lionel-** [comment]
That's a strange one, something in the environment / context of R CMD check may cause the failure. Hopefully you found a solution!
