### ISSUE TITLE
Minimise UI

### ISSUE THREAD

**Issue by hadley** [r-lib/vdiffr#15]
It'd be great if type & case could be side-by-side so you could see more of the plot when it's in a narrow window.  Consider using [miniUI](https://github.com/rstudio/miniUI) ?

<img width="488" alt="screen shot 2017-02-09 at 1 16 43 pm" src="https://cloud.githubusercontent.com/assets/4196/22799074/06422a5a-eeca-11e6-8841-2147b57561f4.png">

**Comment by hadley** [comment]
I don't find the break down of type and case that useful. I think you could just put the type in parenthesis at the end of the case ("padding-in-legend-box (mismatch)"), and maybe tweak the tabs for new + orphaned

**Comment by lionel-** [comment]
vdiffr now uses testthat 3e snapshots for case management (see #107). This comes with its own minimal app from https://github.com/r-lib/diffviewer/
