### ISSUE TITLE
RUnit support?

### ISSUE THREAD

**Issue by eddelbuettel** [r-lib/vdiffr#2]
Would it be possible to not require testthat?

**Comment by lionel-** [comment]
Probably. I would accept a PR for this :)

**Comment by eddelbuettel** [comment]
Challenge accepted :)   Let me download / install and take a look over the next few days.

Loving all your ESS work by the way.

**Comment by lionel-** [comment]
Is camelCase standard for packages using RUnit? If so, you can add a new expectation function like `checkDoppelganger()`.

Then the key part is to silently run all the tests with the case collecter active.

We should also come up with a UI for choosing the kind of test suite to run. We could do it automatically by checking the package deps in the DESCRIPTION file. This will work as long as the tested package does not depend on both testthat and RUnit, which I guess must be a pretty rare corner case.

**Comment by eddelbuettel** [comment]
Agreed that few packages should depend on both. In most cases it is probably a Suggests: for either.

RUnit is also back under active (new) maintenance so we should be able to get help from there.

**Comment by lionel-** [comment]
This is now out of scope for vdiffr as we have switched to testthat 3e snapshots for case management.

However it would be easy for a third party package (maybe tinytest or an extension package?) to use vdiffr for deterministic generation of reproducible SVGs by wrapping around `vdiffr::write_svg()`.
