### ISSUE TITLE
Use different expectation wrapper?

### ISSUE THREAD

**Issue by hadley** [r-lib/vdiffr#32]
If instead of `test_that()` vdiffr used (say) `visualise_that()`, when managing cases, we'd only need to run the visual tests, not all tests

**Comment by lionel-** [comment]
It would be cleaner not to parse the test files for `visualise_that` blocks and rely on normal interpretation instead.

We could implement this by signalling a specific condition before running the `test_that()` code, say `testthat_condition_test_start`. Then we could install a calling handler for that condition and signal a `skip` from there. If this sounds reasonable, I'll open an issue.

**Comment by lionel-** [comment]
@jimhester WDYT about signalling a condition at the start of `test_that()` blocks, so they could be selectively skipped?

**Comment by TimKDJ** [comment]
Being able to selectively run visual tests would be great. We have a large test suite and it takes some time to run everything. I cannot think of a better solution than putting conditional skip's at everything that is not a plot, which I would really rather avoid. 
Is there a better way for me to go about this? Or are there still plans to implement this officially?

**Comment by lionel-** [comment]
You can set the `VDIFFR_RUN_TESTS` environment variable to `"false"` to skip all vdiffr tests.

**Comment by TimKDJ** [comment]
I meant only testing plots, though, not only skipping them. Maybe I wasn't clear enough :)

**Comment by lionel-** [comment]
I'm not sure I understand but it sounds like a conditional skip is the way to go then?

**Comment by TimKDJ** [comment]
Hmm, I guess I should have pointed out I'm specifically talking about `vdiffr::manage_cases`. We use this to test our plots when we change a plot dependency. In these cases we are not interested in the other unit tests, but as it stands they must still be run nonetheless (because of how `vdiffr::manage_cases` works).

**Comment by lionel-** [comment]
Ah you can filter for specific testthat contexts using the `filter` argument.

**Comment by TimKDJ** [comment]
Yep that's nice functionality and I use it too, but it only works across files, not within files (all tests within a file are run, regardless of being a visual test or not). Each of our test files contains tests related to a type (e.g., "ANOVA", "One Sample T-Test") and visual and non-visual tests reside in the same file. 
So I guess the options for my situation at present are conditional skips or separating the visual tests from the other tests.

**Comment by lionel-** [comment]
This is probably out of scope for vdiffr now that we have switched to testthat 3e snapshot management.
