### ISSUE TITLE
Provide ability to show *all* cases in `manage_cases()`

### ISSUE THREAD

**Issue by clauswilke** [r-lib/vdiffr#38]
It would be really helpful if `manage_cases()` could get the option to show all cases, not just the ones that have been validated. As things currently stand, it's essentially not possible to look at the cases that pass.

**Comment by nathancday** [comment]
I'm gonna try and tidy-dev-day tackle this

**Comment by lionel-** [comment]
Great! It would probably make sense to show those in a new "Validated" category in the "Type" dropdown menu. The validation buttons should be grayed out.

**Comment by nathancday** [comment]
got it
