### ISSUE TITLE
vdiffr on Travis

### ISSUE THREAD

**Issue by zzawadz** [r-lib/vdiffr#41]
How to use vdiffr on Travis? It seems that the section on Travis is missing in the README. I tried to run it, but it seems that all vdiffr's tests are skipped.

**Comment by lionel-** [comment]
We are between releases so you need to add vdiffr on Remotes, see the ggplot2 repo: https://github.com/tidyverse/ggplot2/blob/master/.travis.yml

**Comment by zzawadz** [comment]
I've added those lines, and it works:
```
# work around temporary travis + R 3.5 bug
r_packages: devtools

# Install manually because dev vdiffr is not compatible with Appveyor yet
r_github_packages: lionel-/vdiffr
```

Thanks.

**Comment by lionel-** [comment]
Let's keep the issue open until the release.

**Comment by lionel-** [comment]
Though a simple `Remotes: lionel-/vdiffr` field in DESCRIPTION should now work, the Windows situation has been fixed.

**Comment by lionel-** [comment]
Now on CRAN!
