### ISSUE TITLE
AppVeyor badge on README shows "unknown"

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/vdiffr#58]
It seems the AppVeyor's project is still on `lionel-/vdiffr`, not on `r-lib/vdiffr`. Maybe you need to set up again?

https://ci.appveyor.com/project/lionel-/vdiffr

**Comment by lionel-** [comment]
Now fixed, thanks!

**Comment by yutannihilation** [comment]
Thanks for fixing!
