### ISSUE TITLE
Support htmlwidgets

### ISSUE THREAD

**Issue by cb4ds** [r-lib/vdiffr#60]
It would be great if vdiffr would support htmlwidgets natively in expect_doppleganger.  Htmlwidgets are extensively used and extended so native support for this would really go a long way to help with creating test suites for those packages that extend or rely heavily on htmlwidgets such as CanvasXpress.

**Comment by cb4ds** [comment]
I'll be working on this during **_tidy-dev-day_**

**Comment by lionel-** [comment]
Can you come and find me please?

**Comment by lionel-** [comment]
This seems out of scope for vdiffr currently.
