### ISSUE TITLE
`manage_cases()` "progress bar" doesn't respect console width after RStudio update

### ISSUE THREAD

**Issue by echasnovski** [r-lib/vdiffr#66]
I updated today to RStudio 1.2.1335 and "progress bar" of `manage_cases()` (the one with `.`, `o`, `X`, and `N`) doesn't seem to respect console width very well. After reaching console's right side "progress bar" doesn't go on a new line (like it used to). Here is a screenshot of current output where it goes very far to the right in first and last lines (all symbols outside the view are `.`):

![vdiffr_progress-bar-issue](https://user-images.githubusercontent.com/24854248/57022617-5a45c100-6c38-11e9-9178-c4b260aead85.png)

This problem doesn't occur in RStudio 1.1.463 (I reinstalled it with all the same R and package versions): no "progress symbol" appeared outside of current console width.

I am not really sure if that is a problem with vdiffr implementation or RStudio change, but decided to create issue anyway.

**Comment by lionel-** [comment]
Not sure why the output changed across versions. In general it's not a good idea to output long lines, so we should probably insert newlines after `getOption("width")` is reached, it would probably solve the issue.

**Comment by echasnovski** [comment]
Adding usage of private result counter [here inside `vdiffrReporter`](https://github.com/r-lib/vdiffr/blob/4561787efdb7fe6f2c3d0f6ff4f751d148dcecf3/R/testthat-reporter.R#L75) and resetting it (while also doing `cat("\n")`) after it gets to be equal to `getOption("width")` solved the issue. It works on both RStudio 1.2.1335 and 1.1.463. Lines are slightly shorter than console panel, but have exactly `getOption("width")` symbols. In RStudio 1.1.463 they stretched all the way to the right scroll bar.

Is that what you had in mind? I can make a PR with this solution.

**Comment by lionel-** [comment]
That'd be great!
