### ISSUE TITLE
Using theme() to position legend in function defeats testing with theme_test()

### ISSUE THREAD

**Issue by gavinsimpson** [r-lib/vdiffr#74]
In trying to understand why some of reference figures produced with `manage_cases()` use `theme_grey()` and some a simpler theme (presume `theme_test()`), I realised that any use of `theme()`, even if just to fix the position of a legend (which can't be done any other way?) seems to defeat the use of the test theme.

For example, I have the following to turn off a legend by default (user can turn it back on)

```r
plt <- plt + guides(colour = "none")
```
If I switch to the alternative

```r
plt <- plt + theme(legend.position = "none")
```

in my function the visual tests fail. In the first case I get `theme_test()` in the second I get `theme_grey()`.

Is there any way to reliably use the simple test theme whilst using `theme()` in a function?

I appreciate that in the specific case above I can use `guides()` but what if I want to force a specific legend.position:

```r
plt <- plt + theme(legend.position = "bottom")
```

**Comment by lionel-** [comment]
just a guess but maybe `plt + theme_test() + theme(...)`?

**Comment by gavinsimpson** [comment]
The `theme(...)` bit is being done inside the function in the package so I don’t want to hard code a theme there. But I could try and explicitly add `+ theme_test()` in my check code to see if that works.
