### ISSUE TITLE
vdiffr is not aware of the testthat's context without context()

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/vdiffr#81]
testthat encourages to remove `context()` as of version 2.1.0 (see https://testthat.r-lib.org/news/index.html#reporters). But, after I removed `context("foo")` from `tests/testthat/test-foo.R`, vdiffr doesn't recognize the existing images.

- actual path: `tests/fig/foo/case1.svg`
- vdiffr's expectation?: `tests/fig/case1.svg`

**Comment by lionel-** [comment]
I think this is a duplicate of #71.

**Comment by yutannihilation** [comment]
Oh, true. Sorry for not finding it...
