### ISSUE TITLE
Setting height and width on widgets

### ISSUE THREAD

**Issue by gustavdelius** [r-lib/vdiffr#84]
The htmlwidgets accept a `height` and a `width` argument, see https://rdrr.io/cran/vdiffr/man/htmlwidgets.html. The implementation of the widgets however appear to ignore these arguments. Am I right in assuming that they are not yet implemented? If so, it might be wise to indicate that in the help page.

**Comment by lionel-** [comment]
The widgets were removed from vdiffr in favour of https://github.com/r-lib/diffviewer.
