### ISSUE TITLE
vdiffr doesn't work with covr::file_coverage()

### ISSUE THREAD

**Issue by rorynolan** [r-lib/vdiffr#87]
Not sure whether this is a vdiffr issue or a covr issue, but it's because `is_collecting()` is `TRUE` in `covr::package_coverage()` but `FALSE` in `covr::file_coverage()`, so vdiffr tells you you're in interactive mode when you call `covr::file_coverage()`.

**Comment by lionel-** [comment]
Should be fixed by the switch to testthat 3e snapshots in #107.
