### ISSUE TITLE
Github action check - macOS-latest (devel) - Package suggested but not available: ‘vdiffr’

### ISSUE THREAD

**Issue by stemangiola** [r-lib/vdiffr#91]
Thanks for the package.

In my Github action checks for the pull-request https://github.com/stemangiola/tidyHeatmap/pull/44 I receive this error for **macOS-latest (devel)**

 Package suggested but not available: ‘vdiffr’

And here https://cran.r-project.org/web/checks/check_results_vdiffr.html I don't see any MacOS build.

Do you have any idea of what can be the source of the problem?

**Comment by lionel-** [comment]
Sorry I don't know.

**Comment by lionel-** [comment]
These are usually temporary problems.
