### ISSUE TITLE
Make vdiffr compatible with edition 3 of testthat

### ISSUE THREAD

**Issue by rfaelens** [r-lib/vdiffr#96]
**Current behaviour:**
When running using `vdiffr::manage_cases()`, `vdiffr` creates svg files in `tests/figs`. The `.context` attribute from testthat::get_reporter is NULL.
When running using `devtools::test()`, `vdiffr` searches svg files in `tests/figs/testName`. The `.context` attribute from testthat::get_reporter is NULL.

`devtools::test()` therefore consistently reports the figure was not generated yet.

**Expected behaviour:**
Lacking a context, the vdiffrReporter should use the filename as the base context.

**Required change:**

`testthat` edition 3 actively discourages from using the explicit `context()` call.
`devtools::test()` adds a base context using the filename.

**Comment by lionel-** [comment]
Fixed by #107.
