### ISSUE TITLE
Using vdiffr on grid table plots from gridExtra::tableGrob

### ISSUE THREAD

**Issue by JauntyJJS** [r-lib/vdiffr#99]
Hi,

Just a naive question. 

Does the function `vdiffr::expect_doppelganger` able to be used on output from `gridExtra` tables like https://stackoverflow.com/questions/18414001/gridextra-colour-different-rows-with-tablegrob ?

**Comment by lionel-** [comment]
You can wrap the creation of a plot in a function, and pass that function to expect-doppelganger.
